/**
 * IJA - projekt 2013
 * soubor: GamePanel.java
 * Panel pro zobrazeni hry
 * 
 * Autori:
 *         @author Michal Dobes (xdobes13)
 *         @author Jan Kalina   (xkalin03)
 */

package ija.projekt.gui;
import ija.projekt.base.*;
import java.util.Scanner;
import javax.swing.*;

/**
 * Panel hry - je obsahem záložky v GameWindow
 * @author Jan Kalina <xkalin03@stud.fit.vutbr.cz>
 * @author Michal Dobes <xdobes13@stud.fit.vutbr.cz>
 */
public class GamePanel extends javax.swing.JPanel {

    private History history = new History();
    
    /**
     * Konstruktor panelu inicializující hrací plochu
     */
    public GamePanel() {
        initComponents();
        ((Desk)desk).setHistory(history);
        history.setDeskJListAndPlayButton((Desk)desk, historyList, buttonPlay);
        ((Desk)desk).newGame();
    }
    
    /**
     * Hrací plocha
     * @return Hrací plocha
     */
    public Desk getDesk(){
        return (Desk)desk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new Desk();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyList = new JList();
        jToolBar1 = new javax.swing.JToolBar();
        timerField = new javax.swing.JTextField();
        buttonPlay = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        actionField = new javax.swing.JTextField();
        buttonAction = new javax.swing.JButton();

        desk.setLayout(new java.awt.GridLayout(8, 8));

        historyList.setModel(history);
        historyList.setVisibleRowCount(-1);
        historyList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                historyListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(historyList);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        timerField.setText("1000");
        timerField.setPreferredSize(new java.awt.Dimension(60, 40));
        jToolBar1.add(timerField);

        buttonPlay.setText("Přehrát");
        buttonPlay.setFocusable(false);
        buttonPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonPlay);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        actionField.setMinimumSize(new java.awt.Dimension(10, 40));
        actionField.setPreferredSize(new java.awt.Dimension(60, 40));
        jToolBar2.add(actionField);

        buttonAction.setText("Táhnout");
        buttonAction.setFocusable(false);
        buttonAction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionActionPerformed(evt);
            }
        });
        jToolBar2.add(buttonAction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void historyListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_historyListValueChanged
        if(evt.getValueIsAdjusting() == false){ // vyber dokoncen
            if(historyList.getSelectedIndex() != -1){ // neco je vybrano
                try{
                    history.goToHistoryItem(historyList.getSelectedIndex());
                }
                catch(History.HistoryException e){
                    System.err.println("Vyjimka pri skoku na polozku historie:");
                    e.printStackTrace(System.err);
                    JOptionPane.showMessageDialog(null,
                        e.toString(),
                        "Chyba při skoku na položku historie",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_historyListValueChanged
    
    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        if(history.isPlayingHistory()){
            history.stopPlayingHistory();
        }else{
            try{
                int timerValue = Integer.parseInt(timerField.getText());
                history.playHistory(timerValue);
            }
            catch(NumberFormatException e){
                System.err.println("Chybne zadany interval prehravani!");
                JOptionPane.showMessageDialog(null,
                        "Zadaný interval přehrávání není zadaný správně!",
                        "Chybný interval přehrávání",
                        JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                System.err.println("Vyjimka pri prehravani partie:");
                    e.printStackTrace(System.err);
                    JOptionPane.showMessageDialog(null,
                        e.toString(),
                        "Chyba při přehrávání partie",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonPlayActionPerformed

    private void buttonActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionActionPerformed
        try{
            // rozlozit "1. a2-b5 c3xd8" na jednotlive tahy
            Scanner s = new Scanner(actionField.getText());
            while(s.hasNext()){
                String move = s.next();
                
                // preskocit "1."
                if(move.charAt(0) >= '0' && move.charAt(0) <= '9'){
                    continue;
                }
                
                doAction(move);
                actionField.setText("");
            }
        }
        catch(Move.MoveException e){
            System.err.println("Chybne zadany tah textem!");
            JOptionPane.showMessageDialog(null,
                "Zadaný tah není ve správné notaci!",
                "Chybně zadaný tah",
                JOptionPane.WARNING_MESSAGE);
        }
        catch(DoActionException e){
            JOptionPane.showMessageDialog(Game.getWindow(),
                e.getMessage(), e.getTitle(), JOptionPane.INFORMATION_MESSAGE);
            System.err.println(e.getMessage());
        }
        catch(Exception e){
            System.err.println("Vyjimka pri skoku podle retezce:");
            e.printStackTrace(System.err);
            JOptionPane.showMessageDialog(Game.getWindow(),
                e.toString(),
                "Chyba při ručně zadaném skoku",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonActionActionPerformed
    
    /** Provedeni jednoho tahu textem */
    private void doAction(String move) throws Move.MoveException, DoActionException{
        
        System.out.println("doAction("+move+")");
        
        // pokud hra jiz skoncila
        if(getDesk().isGameEnded()){
            throw new DoActionException(
                 "Hra již skončila a vítězi bylo pogratulováno.\n"+
                 "Pro novou hru zvolte Hra -> Nová Hra.", "Nelze hrát");
        }

        // pokud jsme v historii
        if(!this.getDesk().getHistory().inPresent()){
            throw new DoActionException(
                 "Snažíte se změnit historii. To není možné.", "Jste včerejší");
        }
        
        // pokud neni uzivatel na tahu
        if(this.getDesk().getPlayer().type() != Player.Type.HUMAN){
            throw new DoActionException(
                 "Nyní je na tahu druhý hráč!", "Nejste na tahu");
        }
        
        Move m = new Move((Desk)desk,move);
        if(m.getSource().getFigure() == null){
            throw new DoActionException(
                 "Na zdrojovém políčku nestojí žádná figurka!", "Nemožný tah");
        }
        if(m.isCapture()){
            if(m.getSource().getFigure().canCapture(m.getDestination())){
                m.getSource().onClick(); 
                m.getDestination().onClick();
            }else{
                throw new DoActionException(
                     "Zadaný tah není možné provést!", "Nemožný tah");
            }
        }else{
            if(m.getSource().getFigure().canMove(m.getDestination())){
                m.getSource().onClick(); 
                m.getDestination().onClick();
            }else{
                throw new DoActionException(
                     "Zadaný tah není možné provést!", "Nemožný tah");
            }
        }
    }
    
    class DoActionException extends Exception {
        private String title;
        public DoActionException(String message, String title){
            super(message);
            this.title = title;
        }
        public String getTitle(){
            return title;
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actionField;
    private javax.swing.JButton buttonAction;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JPanel desk;
    private javax.swing.JList historyList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField timerField;
    // End of variables declaration//GEN-END:variables
}
